### ISSUE TITLE
你好 chromedp可以打开多个 标签页吗，然后可以切换操作吗

### ISSUE THREAD

**Issue by Xuzan9396** [itchin/sq-music-download#2]
chromedp可以打开多个 标签页吗，然后可以切换操作吗

**Comment by itchin** [comment]
可以的，每一个chromedp.WaitNewTarget会捕获一个浏览器空白选项卡，通过chromedp.NewContext在空白选项卡打开新网址。你要操作哪个页面，就对应操作哪个context。

**Comment by Xuzan9396** [comment]
有没有案例，方便发个网址看下吗
